[package]
name = "wiresx_dashboard_companion"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version =  "0.4.31"  }
figment = { version = "0.10", features = ["toml"] }

[profile.release]
opt-level = 3
debug = false
lto = "thin"
