name: Build artifact

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build --release
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: target/release/wiresx_dashboard_companion.exe

  make_readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/extra:latest
        with:
          args: README.md -t pdf -o README.pdf
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: README
          path: README.pdf

  package:
    runs-on: windows-latest
    needs: [build, make_readme]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: exe
      - uses: actions/download-artifact@v3
        with:
          name: README
      - name: Make archive
        run: |
          cp conf-example.toml conf.toml
          Compress-Archive -Path "wiresx_dashboard_companion.exe", "conf.toml", "README.pdf"  -Destination wiresx_dashboard_companion.zip
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: wiresx_dashboard_companion
          path: wiresx_dashboard_companion.zip